name: Checkin

on:
  workflow_dispatch:
  schedule:
    - cron: '13 16 * * *'

permissions:
  contents: read

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run checkin
        run: python main.py
        env:
          cookie: ${{ secrets.COOKIE }}
          stoken: ${{ secrets.STOKEN }}